assembly-versioning-format: '{Major}.{Minor}.{Patch}.{env:GITHUB_RUN_NUMBER ?? 0}'
assembly-file-versioning-format: '{Major}.{Minor}.{Patch}.{env:GITHUB_RUN_NUMBER ?? 0}'

# conventional commits:

major-version-bump-message: |
  (?x)
  ^
  ( build | chore | ci | docs | feat | fix | perf | refactor | revert | style |test )
  ( \( [\w\s-]* \) )?
  ( !: | : .* \n\n ( ( .+ \n ) +\n )? BREAKING CHANGE: \s .+ )
minor-version-bump-message: |
  (?x)
  ^
  ( feat )
  ( \( [\w\s-]* \) )?
  :
patch-version-bump-message: |
  (?x)
  ^
  ( build | chore | ci | docs | fix | perf | refactor | revert | style | test )
  ( \( [\w\s-]* \) )?
  :

branches:
  main:
    regex: ^main$
  other:
    regex: ^(?!main$).+
    mode: ContinuousDeployment
    source-branches:
      - main