name-template: v$RESOLVED_VERSION
tag-template: v$RESOLVED_VERSION
categories:
  - title: 🚀 Features
    labels:
      - feature
  - title: 🐛 Patches
    labels:
      - patch
  - title: 🧰 Chores
    labels:
      - chore
change-template: - $TITLE @$AUTHOR (#$NUMBER)
change-title-escapes: \<*_& # You can add # and @ to disable mentions, and add ` to disable code blocks.
autolabeler:
  - label: patch
    branch:
      - /patch\/.+/
  - label: feature
    branch:
      - /feature\/.+/
  - label: chore
    branch:
      - /chore\/.+/
  - label: chore
    branch:
      - /chore\/.+/
version-resolver:
  major:
    labels:
      - breaking-change
  minor:
    labels:
      - feature
  patch:
    labels:
      - patch
      - chore
  default: minor
template: |
  ## Changes

  $CHANGES
