name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
  - title: '🧰 Chores'
    labels:
      - 'chore'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
autolabeler:
  - label: documentation
    files:
      - '*.md'
  - label: fix
    branch:
      - '/fix\/.+/'
  - label: feature
    branch:
      - '/feature\/.+/'
  - label: chore
    branch:
      - '/chore\/.+/'
  - label: chore
    branch:
      - '/chore\/.+/'
version-resolver:
  major:
    labels:
      - 'breaking-change'
  minor:
    labels:
      - 'feature'
  patch:
    labels:
      - 'fix'
      - 'maintenance'
  default: minor
template: |
  ## Changes

  $CHANGES
