name: MACH-CD
run-name: Deploy ${{ inputs.tag_name || 'the latest version' }} to ${{ inputs.environment }}

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: Version tag (leave empty for latest vesion)
        type: string
        required: false
      environment:
        description: Deloyment environment
        type: environment
        required: true
        default: Production
      action:
        description: Action (enter 'deploy' or 'destroy')
        type: string
        required: true

jobs:
  cdk:
    name: CDK
    permissions:
      contents: read
      id-token: write
    secrets: inherit
    uses: efteling/mach-shared/.github/workflows/_cd-cdk.beta.yml@main
    with:
      tag_name: ${{ inputs.tag_name }}
      environment: ${{ inputs.environment }}
      action: ${{ inputs.action }}