name: MACH-CI
run-name: Build ${{ inputs.branch_name || github.head_ref || github.ref_name }} and deploy to ${{ (inputs.branch_name || github.head_ref || github.ref_name) == 'main' && 'Staging' || 'Development' }}

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: Branch name (leave empty for main branch)
        type: string
        required: false
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    branches:
      - main
  push:
    branches:
      - main
    paths-ignore:
      - .github/**
      - '**.md'

jobs:
  cdk:
    name: CDK
    permissions:
      contents: write
      id-token: write
      checks: write
      packages: write
    secrets: inherit
    uses: efteling/mach-shared/.github/workflows/_ci-dotnet-cdk.beta.yml@main
    with:
      ref: ${{ format('refs/heads/{0}', inputs.branch_name || github.head_ref || github.ref_name) }}
      environment: ${{ (inputs.branch_name || github.head_ref || github.ref_name) == 'main' && 'Staging' || 'Development' }}